#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : nv-codec-headers
Version  : 12.0.16.0
Release  : 1
URL      : https://github.com/FFmpeg/nv-codec-headers/releases/download/n12.0.16.0/nv-codec-headers-12.0.16.0.tar.gz
Source0  : https://github.com/FFmpeg/nv-codec-headers/releases/download/n12.0.16.0/nv-codec-headers-12.0.16.0.tar.gz
Summary  : FFmpeg version of Nvidia Codec SDK headers
Group    : Development/Tools
License  : MIT
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: build.patch

%description
FFmpeg version of headers required to interface with Nvidias codec APIs.
Corresponds to Video Codec SDK version 12.0.16.

%package dev
Summary: dev components for the nv-codec-headers package.
Group: Development
Provides: nv-codec-headers-devel = %{version}-%{release}
Requires: nv-codec-headers = %{version}-%{release}

%description dev
dev components for the nv-codec-headers package.


%prep
%setup -q -n nv-codec-headers-12.0.16.0
cd %{_builddir}/nv-codec-headers-12.0.16.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1680206830
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1680206830
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/ffnvcodec/dynlink_cuda.h
/usr/include/ffnvcodec/dynlink_cuviddec.h
/usr/include/ffnvcodec/dynlink_loader.h
/usr/include/ffnvcodec/dynlink_nvcuvid.h
/usr/include/ffnvcodec/nvEncodeAPI.h
/usr/lib64/pkgconfig/ffnvcodec.pc
